Repository AY2122S1-CS2103T-W16-4/tp, pull requests merged in 2021-10, with the labels that each got.

#82 Fixes bug in assignedTaskIds during merging
  src/main/java/seedu/address/model/person/Person.java
Labels: bug

#87 Add List<Exam> to Person model
  src/main/java/seedu/address/logic/commands/persons/EditPersonCommand.java
  src/main/java/seedu/address/logic/parser/persons/AddPersonCommandParser.java
  src/main/java/seedu/address/model/person/Exam.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Story

#98 Update docs
  docs/UserGuide.md
  docs/team/tanhuakun.md
Labels: documentation, type.Task

#100 Add explanation of `UniqueId` implementation in DG
  docs/DeveloperGuide.md
  docs/diagrams/UniqueIdDiagram.puml
  docs/images/UniqueIdDiagram.png
Labels: documentation

#101 Add the interface `TaskAssignable`
  src/main/java/seedu/address/model/TaskAssignable.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/person/Person.java
Labels: enhancement
