Repository AY2122S1-CS2103T-W16-4/tp, pull requests merged in 2021-11, with the labels that each got.

#198 Update UI on the landing page
  docs/images/Ui.png
Labels: documentation, type.Bug

#201 Fix documentation bug
  docs/AboutUs.md
  docs/UserGuide.md
Labels: bug, documentation, severity.VeryLow

#202 Edit User Guide to fix documentation for some commands
  docs/UserGuide.md
Labels: documentation, severity.Medium

#197 Fix issues with Indexes
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/persons/EditPersonCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/ValidateUtil.java
  src/main/java/seedu/address/logic/parser/groups/AddGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/groups/DeleteGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/groups/GroupAddLessonParser.java
  src/main/java/seedu/address/logic/parser/groups/GroupRemoveLessonParser.java
  src/main/java/seedu/address/logic/parser/groups/ViewGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/persons/DeletePersonCommandParser.java
  src/main/java/seedu/address/logic/parser/persons/EditPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/persons/PersonAddExamParser.java
  src/main/java/seedu/address/logic/parser/persons/PersonAddLessonParser.java
  src/main/java/seedu/address/logic/parser/persons/PersonRemoveExamParser.java
  src/main/java/seedu/address/logic/parser/persons/PersonRemoveLessonParser.java
  src/main/java/seedu/address/logic/parser/persons/ViewPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/tasks/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/tasks/AssignTaskToGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/tasks/AssignTaskToPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/tasks/DeleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/tasks/EditTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/tasks/MarkTaskDoneStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/tasks/MarkTaskUndoneStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/tasks/UnassignTaskFromGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/tasks/UnassignTaskFromPersonCommandParser.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/DeletePersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditPersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ViewPersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/groups/AddGroupCommandParserTest.java
  src/test/java/seedu/address/logic/parser/groups/DeleteGroupCommandParserTest.java
  src/test/java/seedu/address/logic/parser/groups/ViewGroupCommandParserTest.java
  src/test/java/seedu/address/logic/parser/persons/PersonAddExamParserTest.java
  src/test/java/seedu/address/logic/parser/persons/PersonRemoveExamParserTest.java
  src/test/java/seedu/address/logic/parser/persons/PersonRemoveLessonParserTest.java
Labels: type.Bug, severity.High

#203 Update example in 'add task' command in UG and Add screenshots for few features in UG
  docs/UserGuide.md
  docs/images/imagesInUG/group-add.png
  docs/images/imagesInUG/student-addlesson.png
  docs/images/imagesInUG/student-view.png
  docs/images/imagesInUG/task-edit.png
  docs/images/imagesInUG/task-find.png
Labels: type.Bug

#204 Fix help command to display the correct URL
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Bug

#205 Update accurate examples inside Result Display Panel for task commands
  src/main/java/seedu/address/logic/commands/tasks/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/tasks/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/tasks/EditTaskCommand.java
  src/main/java/seedu/address/logic/parser/tasks/EditTaskCommandParser.java
Labels: type.Bug

#207 Update dev guide
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/diagrams/LessonDiagram.puml
  docs/diagrams/ViewTypes.puml
  docs/images/LessonDiagram.png
  docs/images/ViewTypes.png
  docs/team/tanhuakun.md
Labels: documentation, type.Task

#208 Update the PPP page and AboutUs.md
  docs/AboutUs.md
  docs/UserGuide.md
  docs/team/eltonyeh.md
Labels: documentation

#209 Update PPP
  docs/AboutUs.md
  docs/team/Neha-5678.md
Labels: documentation

#214 Populate sample data with other important details
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/tasks/EditTaskCommand.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: enhancement, priority.Medium

#213 Change the implementation of `Person#isSamePerson()`
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/persons/AddPersonCommand.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/EditPersonCommandTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: bug

#215 Fix messages displayed for student and group commands
  src/main/java/seedu/address/logic/commands/groups/DeleteGroupCommand.java
  src/main/java/seedu/address/logic/commands/groups/ViewGroupCommand.java
  src/main/java/seedu/address/logic/commands/persons/AddPersonCommand.java
  src/main/java/seedu/address/logic/commands/persons/DeletePersonCommand.java
  src/main/java/seedu/address/logic/commands/persons/EditPersonCommand.java
  src/main/java/seedu/address/logic/commands/persons/FindPersonCommand.java
  src/main/java/seedu/address/logic/commands/persons/ViewPersonCommand.java
Labels: severity.Medium

#220 Update User Guide
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/imagesInUG/group-addDavidInGroup.png
  docs/images/imagesInUG/labelledUI.png
  docs/images/imagesInUG/student-addDavid.png
  docs/images/imagesInUG/student-viewDavid.png
Labels: priority.High

#222 Add tests for group storage
  src/test/java/seedu/address/logic/commands/tasks/EditTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/tasks/FindTaskCommandTest.java
  src/test/java/seedu/address/model/id/UniqueIdTest.java
  src/test/java/seedu/address/storage/JsonAdaptedGroupTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/GroupBuilder.java
  src/test/java/seedu/address/testutil/TypicalGroups.java
  src/test/java/seedu/address/testutil/TypicalObjects.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: priority.Medium

#236 Update DG, UG and PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/EditTaskSequenceDiagram.puml
  docs/images/imagesInUG/group-addDavidInGroup.png
  docs/images/imagesInUG/student-addDavid.png
  docs/team/neha-5678.md
  src/main/java/seedu/address/logic/commands/tasks/FindTaskCommand.java
  src/main/java/seedu/address/logic/commands/tasks/ListTaskCommand.java
Labels: documentation

#238 Update PPP with hyperlinks
  docs/team/neha-5678.md
Labels: documentation

#241 Add group task completion commands as future feature
  docs/UserGuide.md
Labels: documentation

#243 Update task assignment implementation in DG
  docs/DeveloperGuide.md
  docs/diagrams/TaskAssignment.puml
  docs/images/TaskAssignmentDiagram.png
Labels: documentation

#246 Edit UML diagrams
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
Labels: documentation

#244 Update UG
  docs/UserGuide.md
Labels: documentation

#247 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/UiClassDiagram.png
Labels: documentation

#250 Update PPP
  docs/team/eltonyeh.md
Labels: documentation

#252 Update UG
  docs/UserGuide.md
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/EditTaskSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/imagesInUG/task-add.png
Labels: documentation

#253 Update portfolio again
  docs/team/eltonyeh.md
Labels: documentation

#254 Try to make ppp be in two page angrily
  docs/team/eltonyeh.md
Labels: documentation

#262 Edit UG to include line break
  docs/UserGuide.md
  docs/team/neha-5678.md
Labels: documentation

#251 Update model diagram and description
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram2.puml
  docs/diagrams/ModelClassDiagram3.puml
  docs/images/ModelClassDiagram.png
  docs/images/ModelClassDiagram2.png
  docs/images/ModelClassDiagram3.png
Labels: documentation

#263 Fix documentation bug and a message bug for task assigning command
  docs/UserGuide.md
  docs/team/eltonyeh.md
  src/main/java/seedu/address/logic/commands/tasks/AssignTaskCommand.java
  src/main/java/seedu/address/logic/commands/tasks/ManageTaskAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/tasks/UnassignTaskCommand.java
Labels: bug, documentation

#264 Add some page breaks for the UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#266 Add more page breaks to the UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation
